[package]
name = "composite_rapid"
version = "0.1.0"
authors = ["Sebastian Holzapfel <seb.holzapfel@data61.csiro.au>"]

[dependencies]
futures = "*"
byteorder = "*"
sdl2 = "*"
flame = "0.2.2"
flamer = "^0.2.3"
